#!/usr/bin/env python

import re


a='LNVEQSPQSLHVQEGDSTNFTCSFPSSNFYALHWYRWETAKSPEALFVMTLNGDEKKKGRISATLNTKEGYSYLYIKGSQPEDSATYLCARNTGNQFYFGTGTSLTVIPNIQNPDPAVYQLRDSKSSDKSVCLFTDFDSQTNVSQSKDSDAYITDKTVLDMRSMDFKSNSAVAWSNKSDFACANAFNNSIIPEDTFFPS'
b='MGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLIHYSVGAGITDQGEVPNGYNVSRSTTEDFPLRLLSAAPSQTSVYFCASSPVTGGIYGYTFGSGTRLTVVEDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWWVNGKEVHSGVSTDPQPLKEQPALNDSRYCLSSRLRVSATFWQNPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGRAD'

A_CDR1_pattern=r'C[A-Z]{1,17}(WY|WF)'
B_CDR1_pattern=r'C[A-Z]{1,17}(WY|WF)'

A_CDR3_pattern=r'C[A-Z]{1,33}(FG|WG)'
B_CDR3_pattern=r'C[A-Z]{1,33}(FG)'

B_CDR2_pattern=r'C[A-Z]{1,62}(L)'

res = re.search(A_CDR1_pattern,a)
if res:
	A_CDR1 = res.group()[1:-2]
	print A_CDR1

res = re.search(A_CDR3_pattern,a)
if res:
	A_CDR3 = res.group()[1:-2]
	print A_CDR3

res = re.search(B_CDR1_pattern,b)
if res:
	B_CDR1 = res.group()[1:-2]
	print B_CDR1

res = re.search(B_CDR3_pattern,b)
if res:
	B_CDR3 = res.group()[1:-2]
	print B_CDR3

res = re.search(B_CDR2_pattern,b)
if res:
	B_CDR2 = res.group()[1:-2]
	print B_CDR2
